### PR TITLE
Improve boss code

### PR DESCRIPTION
**Pull request by flip40**
- Added a "Boss wave/ frame" square to the LevelController editor.
- Updated Scrolling
  - Enemies start in default world space, and move into foreground on spawn (enter screen).
  - Allows enemies to move within the screen without worrying about needing to move with it (important for bosses).
  - Main Scroll script moved from Player to foreground.
- Updated the first state of the TestBossAI.
  - Starts at top right of screen, shoots while moving down, fires missiles at bottom, then shoots again while moving back up.
  - Always starts on state = 0, temporary for demo / testing until other states are fixed.
- Improved Timer class with "fun" code changes (not necessary, but I like them).
  - All functions `return this`, allowing for method chaining: `Timer.Reset().Begin();`
  - Added operator overrides for gt, gte, lt, lte to shorthand comparisons. Changes `Timer.time < 2f` to `Timer < 2f`.
- Duct Taped TrackingAI
  - Forgot to actually set this.team to its GameObject's Team component, resulting in tracking as if belonging to no team.
  - Patched odd behavior of missiles that are rotated 180y. Something odd with the rotation angle and the cross value for turn direction causes missiles to turn away from their target when rotated to certain angles. Fixed by simply swapping the sign for missiles who are 180y. This can and will break on any object rotated to a y value that is not 0 or 180, though there is no practical reason to have other y rotations in 2d. Happy to get a proper fix though if anyone can figure out the proper vector math required.

### CODE REVIEW

**Comment by ghost** [comment]
Cool, will look through this later today

Edit: Ok once again too tired to look through this today >_>. Striving for during the morning tmw

**Comment by ghost** [comment]
Need to also add in the changed prefabs

**Comment by flip40** [comment]
Oh,woops! I'll add the missing prefabs when I get home.

**Comment by flip40** [comment]
Prefabs added. Also includes the TagManager.asset, as I added a tag for the Foreground prefabs to use to make them easy to find in the case that we end up with multiple foreground prefabs in use.

**Pull request merged**
