### PR TITLE
initial weapon script

### PR DESCRIPTION
**Pull request by ghost**
attached to player or enemy game objects

### CODE REVIEW

**Comment by flip40** [comment]
I think we should keep bullettime as part of the Weapon class, not Bullet (and maybe rename to refireRate or something). My thought on it is that the Bullet only cares what to do once it has been fired, but the Weapon determines how (and what kind of) Bullet is fired. For example if we had a Shotgun Weapon, it could fire Bullets in a spread (or Missiles...), but the same Missile and Bullet could also be used in a Machine Gun Weapon, which fires a single Bullet, but very rapidly.

**Comment by ghost** [comment]
Yeah that makes more sense. Will make that change and try and squash these commits into one

**Comment by ghost** [comment]
Also moved bullet delay into weapon (since it may vary based on weapon? Change depending on our game).

**Comment by flip40** [comment]
Yeah, those two should go together (bullettime is the actual counter that goes to bulletdelay). Merging...

**Pull request merged**
