### PR TITLE
Weapon as gameobject

### PR DESCRIPTION
**Pull request by ghost**
And scene update

Also noticed I have some changes made previously here. Don't want to redo the changes I just made >_>. They should be harmless though

### CODE REVIEW

**Comment by flip40** [comment]
Good so far, but I think we should go a bit further... Instead of having the weapon already attached as a child of the player, lets instead instantiate the weapon on Player.Start() and set it's parent (would be something like weapon.parent = this.gameobject). Also have a weapon variable that is just public GameObject weapon that can hold the weapon prefab like the Weapon holds bullet prefabs.

Doing this means we can make multiple weapon prefabs and assign these to the player's weapon variable, allowing easier editing of the weapon or swapping of Weapons.

There is definitely more we would need to do to optimize a system like this but I _think_ it seems like the best way to go. The more modularity we have, the easier it is to swap things out on the fly via the editor.

(Just as an example of the optimizations we will need, swapping weapons by Destroy(); Instantiate(); would be costly, but at the moment we don't have multiple weapons either... the solution however would be to simply Instantiate **new** weapons, and then rely on SetActive to swap weapons)

**Comment by ghost** [comment]
Updated the branch. Did the same for Enemy

**Comment by flip40** [comment]
I'll review this tonight ..

**Comment by ghost** [comment]
Ok no rush

**Comment by flip40** [comment]
Grabbing the Weapon component each frame with GetComponent is somewhat inefficient, though that is entirely my fault for insisting on having Weapon as a GameObject so strongly. The initial solution would be to just have a Weapon variable to store the component so we don't have to call it repeatedly, although this also sucks because having a variable for instantiating the game object and one for the component is messy looking. I did some research and apparently (thankfully) Unity can instantiate a GameObject by its attached component (yay!) So I have just changed the GameObject references to Weapon, and returned the shooting to weapon.Shoot(), and so we can get the game object instantiated, and yet only keep track of the Weapon component variable we care about for the Shoot() calls.

Other than that small change, everything looks good, will merge.

**Pull request merged**
